version: '3'
services:
  db:
    build: ./db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db